// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateMemoRequest defines model for CreateMemoRequest.
type CreateMemoRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// Memo defines model for Memo.
type Memo struct {
	Content   string             `json:"content"`
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Title     string             `json:"title"`
	UpdatedAt time.Time          `json:"updated_at"`
}

// UpdateMemoRequest defines model for UpdateMemoRequest.
type UpdateMemoRequest struct {
	Content string `json:"content"`
	Title   string `json:"title"`
}

// CreateMemoJSONRequestBody defines body for CreateMemo for application/json ContentType.
type CreateMemoJSONRequestBody = CreateMemoRequest

// UpdateMemoJSONRequestBody defines body for UpdateMemo for application/json ContentType.
type UpdateMemoJSONRequestBody = UpdateMemoRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List memos
	// (GET /memos)
	ListMemos(ctx echo.Context) error
	// Create a new memo
	// (POST /memos)
	CreateMemo(ctx echo.Context) error
	// Delete a memo
	// (DELETE /memos/{id})
	DeleteMemo(ctx echo.Context, id openapi_types.UUID) error
	// Get a memo by ID
	// (GET /memos/{id})
	GetMemo(ctx echo.Context, id openapi_types.UUID) error
	// Update a memo
	// (PUT /memos/{id})
	UpdateMemo(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListMemos converts echo context to params.
func (w *ServerInterfaceWrapper) ListMemos(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListMemos(ctx)
	return err
}

// CreateMemo converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMemo(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateMemo(ctx)
	return err
}

// DeleteMemo converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteMemo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteMemo(ctx, id)
	return err
}

// GetMemo converts echo context to params.
func (w *ServerInterfaceWrapper) GetMemo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMemo(ctx, id)
	return err
}

// UpdateMemo converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateMemo(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateMemo(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/memos", wrapper.ListMemos)
	router.POST(baseURL+"/memos", wrapper.CreateMemo)
	router.DELETE(baseURL+"/memos/:id", wrapper.DeleteMemo)
	router.GET(baseURL+"/memos/:id", wrapper.GetMemo)
	router.PUT(baseURL+"/memos/:id", wrapper.UpdateMemo)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8SVzU7cMBDHX8Wa9phuQuGAcqNFQisVCbXqCaHKJLOsUfyBPaFdrfLulcfZhWxC20UU",
	"blZm7Jn/bz6yhspqZw0aClCuIVRL1JKPnz1KwnPU9ivetRgofnTeOvSkkF0qawgNG2jlEEoI5JW5gS4D",
	"UtTghKXLwONdqzzWUF72btn2qatsc8Fe32JF8amYw37BK869/iHZvLBexxPUkvADKR0Dju6oeuDbtqqe",
	"cntKVwatq/cMusMiBdwBMhAzCDKF6jub375o8YYyCy5bjaHyypGyBko4uZiLhfVCiqC0a1AQ/iKhUVsh",
	"nWtUJdlxmwtXX5w4J04u5pDBPfqQXjqYFbMiZm0dGukUlHA4K2aHkIGTtGSxeXyYTzfIkiMJjjCvoYQv",
	"KtA5e0SBwVkTEqSPRbHD6lFy+W2ICWymJZ4UoeaL7z0uoIR3+cNc5f1Q5dzH3ZaV9F6uEqohom9tVWEI",
	"i7YRm6S4BKHVWvpVn7dI0roMnA0T2h7mF1L1MNAnW6/20vUnOeMF0Q0bhXyL3QjswYslkHiO+XHH9FOz",
	"Ay7lLKQw+JMBsj11Sb5WdZcatkHCMdFT/t4TddJLjYQ+QHm5BhUDx7aDDIzUsb48zkMa2SNlf9k03dWI",
	"3NF4mlhqyrcWYds3zSr2xdGTN4wlsbCt2cWTFArZo8mmp+YM6e0gFP+9fSbH7zk0z5B6lOJ6JeanPKvt",
	"BNCHrf1qTF9+HYx/Pf+0DorXWQf9f/N5hUzStmPBRvT3mxK1voESlkSuzPPGVrJZ2kDlcXFc5NKp/P4A",
	"uqvudwAAAP//xAACFWsJAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
