/* tslint:disable */
/* eslint-disable */
/**
 * Memo App API
 * API for a simple text memo application
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CreateMemoRequest {
    'title': string;
    'content': string;
}
export interface Memo {
    'id': string;
    'title': string;
    'content': string;
    'created_at': string;
    'updated_at': string;
}
export interface UpdateMemoRequest {
    'title': string;
    'content': string;
}

/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a new memo
         * @param {CreateMemoRequest} createMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMemo: async (createMemoRequest: CreateMemoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createMemoRequest' is not null or undefined
            assertParamExists('createMemo', 'createMemoRequest', createMemoRequest)
            const localVarPath = `/memos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createMemoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a memo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMemo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteMemo', 'id', id)
            const localVarPath = `/memos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a memo by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemo: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getMemo', 'id', id)
            const localVarPath = `/memos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List memos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMemos: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/memos`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a memo
         * @param {string} id 
         * @param {UpdateMemoRequest} updateMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMemo: async (id: string, updateMemoRequest: UpdateMemoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateMemo', 'id', id)
            // verify required parameter 'updateMemoRequest' is not null or undefined
            assertParamExists('updateMemo', 'updateMemoRequest', updateMemoRequest)
            const localVarPath = `/memos/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateMemoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a new memo
         * @param {CreateMemoRequest} createMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createMemo(createMemoRequest: CreateMemoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Memo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMemo(createMemoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.createMemo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a memo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMemo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMemo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.deleteMemo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a memo by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMemo(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Memo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMemo(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.getMemo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List memos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listMemos(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Memo>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMemos(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.listMemos']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a memo
         * @param {string} id 
         * @param {UpdateMemoRequest} updateMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateMemo(id: string, updateMemoRequest: UpdateMemoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Memo>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateMemo(id, updateMemoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.updateMemo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a new memo
         * @param {CreateMemoRequest} createMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createMemo(createMemoRequest: CreateMemoRequest, options?: RawAxiosRequestConfig): AxiosPromise<Memo> {
            return localVarFp.createMemo(createMemoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a memo
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMemo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMemo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a memo by ID
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMemo(id: string, options?: RawAxiosRequestConfig): AxiosPromise<Memo> {
            return localVarFp.getMemo(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List memos
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listMemos(options?: RawAxiosRequestConfig): AxiosPromise<Array<Memo>> {
            return localVarFp.listMemos(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a memo
         * @param {string} id 
         * @param {UpdateMemoRequest} updateMemoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateMemo(id: string, updateMemoRequest: UpdateMemoRequest, options?: RawAxiosRequestConfig): AxiosPromise<Memo> {
            return localVarFp.updateMemo(id, updateMemoRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Create a new memo
     * @param {CreateMemoRequest} createMemoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createMemo(createMemoRequest: CreateMemoRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createMemo(createMemoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a memo
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteMemo(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).deleteMemo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a memo by ID
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getMemo(id: string, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getMemo(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List memos
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listMemos(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).listMemos(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a memo
     * @param {string} id 
     * @param {UpdateMemoRequest} updateMemoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateMemo(id: string, updateMemoRequest: UpdateMemoRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).updateMemo(id, updateMemoRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



